language: python
python:
  - "3.5"
  - "3.6"

services:
  - docker
  - xvfb

install:
  - pip install .
  - pip install nose
  - pip install coverage
  - pip install codecov

# Nvidia not available on travis
script:
  - nosetests -v --with-coverage --cover-package rocker --exclude test_nvidia_glmark2
after_success:
  - codecov